### ISSUE TITLE
Ebean 9.1.1 update? 

### ISSUE THREAD

**Issue by ZeerDonker** [playframework/play-ebean#100]
Hi,

Are you guys planning on publishing the play ebean update to 9.1.1 ? 

Since just changing the version number of the ebean seems to work. 
(It compiled. And I could integrate the local library to my play 2.5 project. )

`  "org.avaje.ebean" % "ebean" % "9.1.1",`

ps: thanks again to @jroper for the build local command.  (in https://github.com/playframework/play-ebean/pull/52 ) 
```
activator publish-local 
sbt +publishLocal plugin/publishLocal
```

**Comment by 0xbaadf00d** [comment]
Could you test with non default source name ?

eg : 

```
db {
    default.driver = "org.postgresql.Driver"
    default.url = "jdbc:postgresql://127.0.0.1/demo"
    default.username = "postgres"
    default.password = "toor"    

    readonly.driver = "org.postgresql.Driver"
    readonly.url = "jdbc:postgresql://127.0.0.1/demo"
    readonly.username = "postgres"
    readonly.password = "toor"
}
```

**Comment by ZeerDonker** [comment]
Yeah, I think I was a bit early. 

(Made the wrong assumption that building locally also tested first)

**Comment by 0xbaadf00d** [comment]
@ZeerDonker I just create a PR for a working version with Ebean 9.1.1
