### ISSUE TITLE
Remove codecov

### ISSUE THREAD

**Issue by 0xbaadf00d** [playframework/play-ebean#103]
Codecov is clearly unused on this project because Codecov can't detect what is tested or not tested. Currently, it just set all merge requests as "Failed" (even if TravisCI return "success").

Please, remove Codecove from this project.

**Comment by wsargent** [comment]
Looks like it was added with

https://github.com/playframework/play-ebean/commit/2a53f03f2914204b01882b69f6aa52895030b74a

@marcospereira any advantage to codecov here?

**Comment by marcospereira** [comment]
The point was to look at the code coverage of this project and see if PRs are improve the test suite. If I remember correctly, at the time I've added it, Codecov was not reporting PRs as failing.

I have no problem to remove it now.

**Comment by 0xbaadf00d** [comment]
thank you @marcospereira

**Comment by schmitch** [comment]
actually I don't see a reason to remove it. It just fails a check, not the test or the cla validator, PR's are still mergeable. And actually `codecov` might improve the test suite, if anybody would write tests for this project, but I guess at the moment the project is not *very* well maintaned, mainly because ebean isn't in use by many people.
And ebean has no useful release policy, I mean the latest releases were: `8.7.1`, then came `8.8.1` and now there is a `9.1.1` actually the latest two were 3 days of.

Personally I wouldn't recommend to use play with ebean and would even prefer to remove it from our docs.

**Comment by 0xbaadf00d** [comment]
Codecove can't improve test suite because is not aware of dependencies.

By exemple, if i use the method `EbeanServer::xxxxxxxx`. Codecov decrease the cover percentage for the projet play-ebean. But is not the job of play-ebean to test `EbeanServer::xxxxxxxx`, is the job of Ebean project.

**Comment by schmitch** [comment]
> Codecove can't improve test suite because is not aware of dependencies.

Doesn't matter if you integrate something in your project you should test it, even if you change the underlying method.
codecov fails because that was NEVER tested. You added a new config but actually the config was never tested.
What codecov is not aware of are scripted tests, that is the only problem, but not a big one, actually.

**Comment by marcospereira** [comment]
It is not about testing and covering Ebean code itself, but testing the code that we wrote for this module and integrates Ebean and Play:

https://github.com/playframework/play-ebean/tree/master/play-ebean/src/main/java/play/db/ebean

I didn't have time to look at codecov configuration, but maybe it is possible to just let it inform us about the coverage without failing the build.

**Comment by 0xbaadf00d** [comment]
@schmitch @marcospereira 

If your goal is to abandon this project, it would be nice to officialize the news. So developers won't continue to submit PRs for nothing. Maybe set this repo as Read-Only would be nice (close PR feature on settings)

Our Organization take the lead on this project. To move quickly, we just need documentation about how to generate package file and publish it on central repository (to be accessible via SBT).

Did you prefer that the repo was transfered or forked ?

![image](https://cloud.githubusercontent.com/assets/1005086/20630071/275c34c8-b32f-11e6-85ad-6bea062cc6bf.png)

**Comment by schmitch** [comment]
Why don't you first try to fork it and try to package/deploy it under your org?

**Comment by 0xbaadf00d** [comment]
ok @schmitch, we mainly use Maven. Is the same process with SBT to publish artifacts ?

**Comment by 0xbaadf00d** [comment]
@schmitch,

 we are publish SNAPSHOT with success, but we can't use it with Play 2.5.10 project. The command `sbt publish` generate and publish the artifact `play-ebean_2.11-16.11-SNAPSHOT` but Play try to download `play-ebean_2.10-16.11-SNAPSHOT` !

**Comment by marcospereira** [comment]
@0xbaadf00d sorry for not being active here. 

I'm currently taking a look at issues and pull requests here so the project could keep up with contributions. I don't think that you need to fork and create your own releases.

**Comment by 0xbaadf00d** [comment]
We have forked last week (https://github.com/payintech/play-ebean) and begin to refactoring code (code style, indentation, missing javadoc, missing scaladoc, ...).

But I think is not a problem to contribute to both. 

The method `EbeanParsedConfig::parseFromConfig` seems really over-complicated related to the job it have to do.

```java
final Config playEbeanConfig = config.getConfig("play.ebean");  // Return always "ebean"
final String defaultDatasource = playEbeanConfig.getString("defaultDatasource");  // Return always "default"
```

The unit test part is too over complicated. In the future, will be possible to run unit test without to have to publish locally play-ebean package ?

**Comment by marcospereira** [comment]
Codecov was removed.
