### ISSUE TITLE
Before releasing final version of 4.0.0, please update to latest ebean version

### ISSUE THREAD

**Issue by KoenDG** [playframework/play-ebean#120]
Seeing at the plugin has reached Release Candidate status, I'd like to recommend picking the latest version of ebean that's out at the moment, which is 10.3.1 and not 10.2.3 as is currently set.
 
In 10.3.1, several commits have been added after 10.2.3, the following being the most impactful additions and bugfixes(in my opinion):

Ebean migrations can not be executed if they contain ';' into a string: https://github.com/ebean-orm/ebean/commit/4064aaf71443b83ec010af7ec83b53e109f8268b

Read the new `@Length` annotation: https://github.com/ebean-orm/ebean/commit/c7cbe4ead86dd279e4019c99c083a438a65f5c56

`@DiscriminatorColumn` columnDefinition is ignored for DDL generation: https://github.com/ebean-orm/ebean/commit/d04954e46f2d657c2db97f6cced34a25020e1668

Create valid migration scripts for non-Postgres databases and `@DbArray` columns.: https://github.com/ebean-orm/ebean/commit/fe9500e6d01b7ae6508ddfd325c10fee288d7a7c

Migration "add column" DDL with check constraint is missing constraint name: https://github.com/ebean-orm/ebean/commit/d0c1ae76f499554399af9e085ae38d92303643af

**Comment by gmethvin** [comment]
Too late, but I upgraded on version 4.0.2. Next time feel free to submit a pull request.

**Comment by KoenDG** [comment]
Ah yeah I saw the update notification on the 4.0.0 ticket and then took my time looking at which commits would be good to include as an example, my bad.
