### ISSUE TITLE
Make release for play framework 2.5.X and Ebean 10.3.2

### ISSUE THREAD

**Issue by wobu** [playframework/play-ebean#121]
A bug in EBean (since 4.X) prohibited an update to a newer play framework since 2.4

Finally we identified this bug and it was fixed in the latest 10.3.2 release of ebean.

See: https://github.com/ebean-orm/ebean/issues/1040

I will provide a pull request with a new versioning branch for playframework 2.5 and Ebean 10.3.2.

It would be nice if you could do an official release with that.

**Comment by PromanSEW** [comment]
I think it may be closed now

**Comment by marcospereira** [comment]
Closing since we now have 3.2.0. :-)
