### ISSUE TITLE
Version 3.1.0 isn't mentioned in the releases list in the readme

### ISSUE THREAD

**Issue by KoenDG** [playframework/play-ebean#123]
I'm assuming it exists for the 2.5.x branch, but it's not mentioned in the list.

**Comment by marcospereira** [comment]
Hi @KoenDG,

Yes, there is a 3.1.0 version released as you can see here:

http://central.maven.org/maven2/com/typesafe/play/play-ebean_2.11/3.1.0/

Do you want to submit a PR to add it to README?

Thanks.

**Comment by KoenDG** [comment]
PR made.

**Comment by PromanSEW** [comment]
I think it may be closed now

**Comment by KoenDG** [comment]
ah yeah sure
