### ISSUE TITLE
Cross build for sbt 0.13 and 1.0

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-ebean#134]

**Comment by jannemann** [comment]
play is pretty much useless without the ebean plugin to us. can someone outline what had to be done?

**Comment by marcospereira** [comment]
Hey @jannemann!

If you want to work on this, start reading the following sbt docs:

1. http://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html
2. http://www.scala-sbt.org/1.x/docs/sbt-1.0-Release-Notes.html

And of course, you can get in touch in our contributors channels here:

https://gitter.im/playframework/contributors

**Comment by jannemann** [comment]
I guess this is way out of my knowledge, sorry
