### ISSUE TITLE
Update to Ebean 10.4.7 / 11.x.x

### ISSUE THREAD

**Issue by PromanSEW** [playframework/play-ebean#138]
https://github.com/ebean-orm/ebean/releases/tag/ebean-10.4.7
https://github.com/ebean-orm/ebean/releases/tag/ebean-11.2.2

**Comment by marcospereira** [comment]
Hey @PromanSEW, do you want to submit a PR here?

Thanks!

**Comment by PromanSEW** [comment]
@marcospereira I think you know how to update Ebean and plugin better.
Maybe you will prefer to separate versions for major update of Ebean (10.x -> 11.x)

**Comment by PromanSEW** [comment]
@marcospereira I will submit PR if you clarify version matrix for branches

**Comment by marcospereira** [comment]
Closed by #142.

**Comment by marcospereira** [comment]
By the way, see release 4.1.0.
