### ISSUE TITLE
Integration with 11.x.x   

### ISSUE THREAD

**Issue by kpysniak** [playframework/play-ebean#141]
Hey,

What are the plans on releasing play-ebean compatible with the latest ebean orm (11.x.x)? There are a number of great changes and improvements. Is there some timeline on that?

Thanks,
Karol

**Comment by PromanSEW** [comment]
Dupe of #138

**Comment by marcospereira** [comment]
Closed by #142.

**Comment by marcospereira** [comment]
By the way, see release 4.1.0.
