### ISSUE TITLE
Regression found with version annotation, requesting ebean version update to 11.14.2

### ISSUE THREAD

**Issue by KoenDG** [playframework/play-ebean#149]
See here: https://github.com/ebean-orm/ebean/issues/1339

And here: https://groups.google.com/forum/#!topic/ebean/9uf5lXsI4AA

Requesting the version for play 2.6.x be updated to at least 11.14.2

If you're currently using play-ebean 4.1.0 and your project uses the `@Version` annotation, it will not work as expected when updating a model with a version different from what is in the database.

Downgrading to play-ebean 4.0.6 is currently the only solution.

**Comment by PromanSEW** [comment]
This issue can be closed

**Comment by KoenDG** [comment]
Ah yes, thanks for reminding me.
