### ISSUE TITLE
How does one configure Ebean to use encryption?

### ISSUE THREAD

**Issue by allnash** [playframework/play-ebean#150]
## Example project?

**Comment by marcospereira** [comment]
Hi @allnash, 

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Of course, the discussion at the forums can lead us to later reopen this issue (or open a new one).

Best.
