### ISSUE TITLE
DOCS Question - What does "do not expect Ebean-generated getter/setters to be available at compilation time." mean?

### ISSUE THREAD

**Issue by rbygrave** [playframework/play-ebean#16]
In the docs under caveats:
>
(1) Because Ebean class enhancement occurs after compilation, do not expect Ebean-generated getter/setters to be available at compilation time. If you'd prefer to code with them directly, either add the getter/setters explicitly yourself, or ensure that your model classes are compiled before the remainder of your project, eg. by putting them in a separate subproject.

What Ebean generated getter/setters is this referring to?  I don't believe there are any methods that Ebean enhancement adds that developers would add themselves.

Cheers, Rob.

**Comment by jroper** [comment]
That should probably be updated - initially we made no distinction between ebean enhancement and Play's own enhancement.  The play-enhancer project generates getters and setters for public fields:

https://github.com/playframework/play-enhancer

**Comment by rbygrave** [comment]
Ok cool.  I'll close this question - thanks.
