### ISSUE TITLE
ebean 11.24.1 is released.

### ISSUE THREAD

**Issue by hshiozawa** [playframework/play-ebean#163]
Ebean 11.24.1 is released.

https://github.com/ebean-orm/ebean/releases/tag/ebean-11.24.1
> Java 11 support with ebean-agent 11.24.1

The new version (11.24.1) supports Java 11. It would be great to use play-ebean with Java 11.

Thanks,
Hajime.

**Comment by PromanSEW** [comment]
When Play 2.7.0 is released this plugin gets update to latest version of Ebean

**Comment by hshiozawa** [comment]
Thank you for the reply.

> When Play 2.7.0 is released this plugin gets update to latest version of Ebean

OK. I got it :-)
