### ISSUE TITLE
DOCS Question - Why not enhance Scala entity beans?

### ISSUE THREAD

**Issue by rbygrave** [playframework/play-ebean#17]
In the docs under caveats:

> (2) Enhancement of direct Ebean field access (enabling lazy loading) is only applied to Java classes, not to Scala. Thus, ...

Perhaps I misunderstand this but is there are reason for not enhancing Scala entity beans?  There is technically no reason why not to from an EbeanORM agent/enhancement perspective to enhance entity beans written in Scala (using scala properties).  

I wonder the reason for this restriction?

Cheers, Rob.

**Comment by jroper** [comment]
Actually, I don't think that's true, I think we do enhance scala beans, again this is probably referring to when we considered the getter/setter generation one and the same with ebean enhancement, we only generated getters/setters for Java beans.  Until #13, what we didn't do was update the product timestamps of enhanced scala classes, causing incremental compilation issues (everything would always be recompiled).

**Comment by rbygrave** [comment]
Ok cool. 

From an Ebean perspective 4.x does not support scala types Seq, Buffer etc so that is a current limitation in writing entity beans in scala (but there should be no limitation regarding the methods that 'scala properties' use instead of the java spec getter/setter).  If I get time I might restore support for that (support for Seq, Buffer and other scala types) in Ebean 4.x.

Closing this question.  
Thanks, Rob.
