### ISSUE TITLE
Update to latest ebean version

### ISSUE THREAD

**Issue by Marc2017** [playframework/play-ebean#170]
Please update to the latest ebean version with the next release. 
There are a couple of bugfixes done in ebean.

(Day of writing it is: ebean: 11.32.1, ebean-agent: 11.27.1)

thanks
marc

**Comment by marcospereira** [comment]
Hey @Marc2017, 

We are not actively working on this repository right now. See the status here: https://github.com/playframework/play-ebean#support

Given that, a pull request would be welcomed here.

**Comment by lapidus79** [comment]
5.0.2 is available
