### ISSUE TITLE
Pool leak while running tests

### ISSUE THREAD

**Issue by comtihon** [playframework/play-ebean#176]
Hi, I have an integration test:
```scala
class IntegrationTest extends PlaySpec with GuiceOneAppPerSuite with BeforeAndAfterEach {

  lazy val application: Application = new GuiceApplicationBuilder().build()

  lazy val injector: Injector = application.injector

  lazy val ebeanServer: EbeanServer = Ebean.getServer(injector.instanceOf(classOf[EbeanConfig]).defaultServer())

  override def beforeEach(): Unit = {
  }

  override def afterEach {
    val db: Database = injector.instanceOf(classOf[Database])
    val conn = db.getConnection()
     // do some cleanup and close the connection
}
```
After I've increased my tests number I've started to get `com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: sorry, too many clients already` when running them all.
I've checked the logs - looks like it spawns two pools and two applications, while closing only one.
logs:
```
[info] application - Creating Pool for datasource 'default'
[info] i.e.c.p.LoadContext - loaded properties from [ebean.properties]
[info] i.e.EbeanVersion - ebean version: 11.15.4
[info] o.j.StatementLogger - SELECT version() AS "version";
<--> here it starts applying evolutions, if they were not applied
[debug] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] application - Creating Pool for datasource 'default'
[info] o.j.StatementLogger - SELECT version() AS "version";
[info] i.e.i.DefaultContainer - DatabasePlatform name:default platform:postgres
<--> here runs my beforeEach and then my test.
[debug] p.a.l.c.ActorSystemProvider - Shutdown application default Akka system: application
[info] application - Shutting down connection pool.
```
As you can see, for each suite I have two pools spawned while only one closed. I have 37 tests now, and the last one is failing, as it can't connect to the database.

What I've tried:
* have application be def, not val. Doesn't help
* use non-lazy app. Doesn't help
* disable evolutions autoapply. Doesn't help. It anyway starts the first datasource, even without evolutions
* using ebeanServer instead of `injector.instanceOf(classOf[Database])` in cleanup. Sometimes it works, sometimes not, as ebeanServer's pool can be already disconnected.

I am using 2.6.12 play, 4.1.3 play-ebean, 2.12.4 scala

**Comment by marcospereira** [comment]
The test you sent has a problem. It is creating a new application for every test, which means it is creating a connection pool, but it is not stopping the application, at least not on the code you sent. Even worse, it is starting two applications for each test (one is created by `GuiceOneAppPerSuite`).

See the documentation here: https://www.playframework.com/documentation/2.7.x/ScalaFunctionalTestingWithScalaTest#Creating-Application-instances-for-testing

Your test should be something like:

```scala
class IntegrationTest extends PlaySpec with GuiceOneAppPerSuite with BeforeAndAfterEach with play.api.test.Injecting {

  lazy val ebeanServer: EbeanServer = Ebean.getServer(inject[EbeanConfig].defaultServer())

  override def beforeEach(): Unit = {
  }

  override def afterEach {
    val db: Database = inject[Database]
    db.withConnection { conn => 
      // do your clean up and connection will be released by Play's Database API
    }
  }
}
```

I'm not sure why do you need an instance of `EbeanServer`, but you may also want to use [`Ebean.execute`](https://ebean.io/apidoc/11/io/ebean/Ebean.html#execute-java.lang.Runnable-).

Finally, our [forums](https://discuss.playframework.com) would be a better place for such questions. Github issues are for reporting bugs and feature requests, not for general discussion and getting help. Given that, I'm closing this.

Best.
