### ISSUE TITLE
Guava 20.0 Dependency via Reflections

### ISSUE THREAD

**Issue by vjkoskela** [playframework/play-ebean#187]
I am using play-ebean_2.13:5.0.2 and noticed that it depends on org.reflections:reflections:0.9.11 which depends on Guava 20.0 which has open CVEs against it and was released Oct-2016. 

There is an open issue against reflections for this:

https://github.com/ronmamo/reflections/issues/222

In this package, the only use of Reflections is in [DefaultEbeanConfig.java#L202](https://github.com/playframework/play-ebean/blob/master/play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java#L202). One option is to drop Reflections and upgrade Guava and leverage its `com.google.common.reflect.ClassPath` to perform classpath scanning. It's not as feature rich as Reflections, but it will get the job done.

Alternatively, since this does not appear to be part of the exposed interfaces, would it be possible to shade Reflections and Guava to avoid any potential package-version conflicts?

**Comment by jmswenski** [comment]
Bumped org.reflections to 0.9.12 in #203
