### ISSUE TITLE
Play 2.7 & evolutions

### ISSUE THREAD

**Issue by GBeushausen** [playframework/play-ebean#188]
Since 2.7 the evolution behaviour has changed, so the application runs before evolutions to the database are done. So all my applications don’t work anymore. In the documentation is the following code to restore the old behaviour:

`import play.api.ApplicationLoader.Context
import play.api.BuiltInComponentsFromContext
import play.api.db.Database
import play.api.db.DBComponents
import play.api.db.HikariCPComponents
import play.api.db.evolutions.EvolutionsComponents
import play.api.routing.Router
import play.filters.HttpFiltersComponents

class AppComponents(cntx: Context)
    extends BuiltInComponentsFromContext(cntx)
    with DBComponents
    with EvolutionsComponents
    with HikariCPComponents
    with HttpFiltersComponents {
  // this will actually run the database migrations on startup
  applicationEvolutions

}`

How does that translate to Java?

**Comment by mkurz** [comment]
@GBeushausen Can you please test again with Play 2.7.5 (or 2.8.2?) I think this should be fixed now.
