### ISSUE TITLE
Support default sbt/maven layout for ddl generation

### ISSUE THREAD

**Issue by willjschmitt** [playframework/play-ebean#195]
Play framework supports using the [maven/sbt default layout](https://www.playframework.com/documentation/2.8.x/Anatomy#Default-sbt-layout) instead of the Play framework layout, which means `conf/` (including `conf/evolutions/**/*.sql` files are moved to the `src/main/resources/evolutions/**/*.sql` path

In order for play-ebean to not generate ddl while testing, it seems there needs to be `conf/evolutions/default/1.sql` or otherwise DDL will run, and that DDL will be found first instead of `src/main/resources/evolutions/default/1.sql`.

I did try to follow the suggestion in #66 to disable DDL generation by adding a config mutation class, which does appear to be run, but the DDL generation still occurs:
```
public class EbeanServerConfigStartup implements ServerConfigStartup {
    public void onStart(ServerConfig serverConfig) {
        serverConfig.setDdlGenerate(false);
        serverConfig.setDdlRun(false);
    }
}
```

The workaround I've gotten to work is to symlink (or make an exact copy of 1.sql) from `conf/evolutions/default/1.sql` to `src/main/resources/evolutions/default/1.sql`, to prevent the DDL creation due to the first evolution being found (without the ebean ddl header).

**Comment by vadimvera** [comment]
Would it be possible to configure this, if implemented, using the DSL in `application.conf`?

Something like:

```javascript
ebean {
  ddlGenerate = false
  ddlRun = false
}
```

**Comment by mkurz** [comment]
@vadimvera So we are basically talking about 

- #366

here? I am right?

If so, in #366 I already point to the files that need to be worked on to the such a config implemented, would you be interested to provide a pull request?

**Comment by mkurz** [comment]
The original issue can not be fixed by setting
```hocon
play.ebean.generateEvolutionsScripts = false
```
See
* https://github.com/playframework/play-ebean/releases/tag/8.1.0
* https://github.com/playframework/play-ebean/releases/tag/7.1.0
