### ISSUE TITLE
Release by tag

### ISSUE THREAD

**Issue by octonato** [playframework/play-ebean#199]
Releasing play-ebean still requires the manual intervention from Lightbend. We should modify the build to enable release by tag from GitHub / Travis. 

play-soap has been recently modified for the same, we should do the same here.

**Comment by renatocaval** [comment]
@lapidus79 / @jmswenski, would you guys want to take on that task? I can assist if needed.

**Comment by ennru** [comment]
see https://github.com/playframework/play-soap/pull/89
