### ISSUE TITLE
[6.2.0-RC4] Models are not enhanced anymore

### ISSUE THREAD

**Issue by PromanSEW** [playframework/play-ebean#228]
I know that Play Enhancer was removed, but how to auto enhance models without getters and setters now?
I checked compiled classes in target/scala-2.13/classes, and Ebean generated methods are only in constructors, other field changes are explicitly assignments as original non-enhanced code

**Comment by mkurz** [comment]
You probably have to add the getters and setters explicitly yourself now (your IDE probably can generate that code for you).
Or you could use lomboks [`@Getter` and `@Setter` annotations](https://projectlombok.org/features/GetterSetter).
Not sure if ebean supports Java records, which would maybe be an option as soon as Play 2.9 is released which will add support for Java 17.

**Comment by PromanSEW** [comment]
@mkurz I already started to migrate from assignments to setters.
Please note in changelog that enhancing is broken, I found this behaviour by accident, while fast-testing model editing before production, fortunately

**Comment by mkurz** [comment]
@PromanSEW I updated the [release notes](https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC4) and the linked them in the [README](https://github.com/playframework/play-ebean) as well, I think that should make users aware of the changes.

**Comment by plouf142** [comment]
If I understand correctly, this also concerns general play projects, right? Or does disabling the play-enhancer only concern the use of ebean?

If general play projects are concerned, the play documentation should be updated (at least https://www.playframework.com/documentation/2.8.x/PlayEnhancer and https://www.playframework.com/documentation/2.8.x/JavaForms#Handling-form-submission), right?

**Comment by mkurz** [comment]
@plouf142 I already removed that docs: https://github.com/playframework/playframework/pull/10884

**Comment by plouf142** [comment]
@mkurz It is not in documention published. Since the modification is only on master branch, it will be on next 2.9 / 3.0 play version ?

**Comment by mkurz** [comment]
> it will be on next 2.9 / 3.0 play version ?

Yes.
