### ISSUE TITLE
Ebean enhancement requires configuration in every module

### ISSUE THREAD

**Issue by seantbrady** [playframework/play-ebean#25]
I'm working on upgrading a large multi-module project from Play 2.2 to Play 2.4.  I spent several hours debugging the elusive "Error injecting constructor, java.lang.IllegalStateException: Bean class com.mycompany.myapp.entities.MyEntity is not enhanced?” error.  The short story is that every module requiring enhancement requires "ebean.default="com.mycompany.*” in its application.conf.  In previous versions of Play, the configuration was taken from whatever project sbt was executing.  Is this change intentional?  If so, why (I’m guessing because that’s how plugins work)?  Can this change be documented in the migration guide and main play-ebean docs?  Or better, perhaps this configuration can be done when including/enabling the plugin (not sure how this works)?

Longer story:
Our Ebean entities are located at “com/mycompany/*”, not the default “models”.  In my current (highly simplified) configuration, I have one root project with ebean.default="com.mycompany.*" and two modules with the SbtEbean plugin enabled.  I turned on logging for the SbtEbean plugin (requires building from source).  When running from the root project, the following logs were created.

ebean-enhance> transform> pkg: models
ebean-enhance> transform> pkg: models
ebean-enhance> transform> pkg: com/mycompany
ebean-enhance> transform> pkg: models
ebean-enhance> transform> pkg: models
ebean-enhance> transform> pkg: com/mycompany

I’m not sure why this cycle runs twice.  However, this leads me to believe that the two modules are defaulting to the model.* classes rather than the com.mycompany.* classes.

**Comment by jroper** [comment]
Hi @seantbrady, I think the new behaviour of sbt-ebean is better than the old behaviour, but it does leave open the issue of what the best practice should be for configuring multi project modules.

Which models to enhance is ultimately configured by the `EbeanKeys.models` task.  So, in your build, you can set:

```scala
EbeanKeys.models := Seq("com.mycompany.*")
```

If you set this for each project, everything should work.  As a convenient default for `models`, we look up the `application.conf` file in the current project, and read the ebean config out of that.  But this obviously doesn't work in a multi module project.

Something however that will work in a multi module project, if you want the configuration to be unified between your build and your configuration, is this.  In each sub project that doesn't have an `application.conf` but does have models to enhance, create a `reference.conf` file.  `reference.conf` is used by Typesafe config for libraries to provide default configuration.  In that, you can use the append operator, eg:

    ebean.default += "com.mycompany.modulea"

And then, make sure that the main project either doesn't include the ebean config, or if it wants to add additional models, that it uses the append operator too.

Unfortunately sbt ebean won't pick this config up yet in RC1, #22 is required for this to work.  But that's another option.

**Comment by seantbrady** [comment]
Thanks.  I've published a SNAPSHOT of play-ebean and sbt-play-ebean to our internal company repo.  The reference.conf approach works well.  Love having play-ebean as a separate library!
