### ISSUE TITLE
Ebean Transformer debug level not configurable

### ISSUE THREAD

**Issue by seantbrady** [playframework/play-ebean#26]
SbtEbean.scala line 61 reads: "val transformer = new Transformer(classpath, “debug=-1”)”.  In order to debug this issue (https://github.com/playframework/play-ebean/issues/25), I had to locally build play-ebean to set “debug=1”.  Is there a way to pass this kind of configuration into the plugin?

**Comment by jroper** [comment]
Not yet, but I agree it should be added.
