### ISSUE TITLE
Ebeans 4.6.2 contains critical bug affecting Scala Models

### ISSUE THREAD

**Issue by mickgiles** [playframework/play-ebean#44]
With a @OneToMany list of items in a Scala model updates to the list are not properly recognized resulting an OptimisticLockException. The bug has been logged here https://github.com/ebean-orm/avaje-ebeanorm/issues/310 and ultimately fixed in 4.7.1
See https://groups.google.com/forum/#!topic/ebean/girmxEK0vnw for more context

The solution is to upgrade play-ebean to use 4.7.1 of the ebeans framework

**Comment by marcospereira** [comment]
This can be easily done without a new release of play-ebean. Just add ebean as a dependency of your application and the old version will be evicted. If there are binary compatibility issues, then we will need to release a new version of play-ebean, which is not the case here (see #46).

**Comment by mickgiles** [comment]
Perfect, thank you! Works great.
