### ISSUE TITLE
Import ebean plugin identifiers

### ISSUE THREAD

**Issue by alex-zykov** [playframework/play-ebean#48]
We migrate our project to play 2.4 and ebean 4.x the migration guide says:
```
All classes in the SBT plugin are now in the package play.sbt, this is particularly pertinent if using .scala files to configure your build. You will need to import identifiers from play.sbt.PlayImport to use play provided configuration elements.
```
But what if we need to import identifiers of SBT Ebean plugin like `playEbeanModels` is it possible to do it? Nothing found in any parts of documentation.

**Comment by jroper** [comment]
To get the imports for Play ebean keys, you need to import the following:

```scala
import play.ebean.sbt.PlayEbean.autoImport._
```
