### ISSUE TITLE
Need to update to latest Play API

### ISSUE THREAD

**Issue by richdougherty** [playframework/play-ebean#49]
We're getting nightly build failures, presumably because play-ebean is returning `F.Promise` but Play now returns `CompletableFuture`.

```
[error] /home/play/deploy/play-ebean/play-ebean/src/main/java/play/db/ebean/TransactionalAction.java:18: call(play.mvc.Http.Context) in play.db.ebean.TransactionalAction cannot override call(play.mvc.Http.Context) in play.mvc.Action
[error]   overridden method does not throw java.lang.Throwable
[error] public F.Promise<Result> call(final Context ctx) throws Throwable {
[error]         return Ebean.execute(new TxCallable<F.Promise<Result>>() {
[error]             public F.Promise<Result> call() {
[error]                 try {
[error]                     return delegate.call(ctx);
[error]                 } catch (RuntimeException e) {
[error]                     throw e;
[error]                 } catch (Throwable t) {
[error]                     throw new RuntimeException(t);
[error]                 }
[error]             }
[error]         });
[error]     }
```

Cc @jroper @dotta.

**Comment by marcospereira** [comment]
@richdougherty I don't get it. The master version of `play.mvc.Action` is still returning a `F.Promise`:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/mvc/Action.java#L24-L27

Which build is failing?

**Comment by richdougherty** [comment]
Sorry, I didn't read the error message properly. The method in play-ebean can't declare `throws Throwable` because of this change:

https://github.com/playframework/playframework/commit/f9e2d1917019f2bb1b2876b464014640965bade1#diff-02a5773c77e32371d3322bbb15c320d7L27

**Comment by marcospereira** [comment]
I can assume the nightly build is running against the master branch of playframework, right? The master branch of play-ebean is building green to me.

**Comment by dotta** [comment]
@marcospereira To reproduce the issue you should have started sbt with `-Dplay.version=2.5.0-SNAPSHOT` (e-bean master is [defaulting to Play 2.4.2](https://github.com/playframework/play-ebean/blob/master/build.sbt#L3))

**Comment by marcospereira** [comment]
Thank you, @dotta. Before fixing this issue, I think we need to release a minor version of play-ebean. We already have some updates and fixes here.

WDYT?

**Comment by dotta** [comment]
Sounds reasonable to me!

**Comment by jroper** [comment]
@marcospereira to answer your question of which build is failing, it's the nightly deploy build which runs here:

http://vegemite.typesafe.com/

This does nightly deployment of snapshots, including documentation to playframework.com, and lives there and not Jenkins because it became too hard to manage credentials in a safe way on the Jenkins instance while also allowing PR validation.
