### ISSUE TITLE
No enhancement with non "models.*" package

### ISSUE THREAD

**Issue by pycloux** [playframework/play-ebean#54]
Hi All,

I am coding a single module project with play 2.4.2 and play-ebean plugin "1.0.0"

My application.conf contains:
```
# Ebean configuration
# ~~~~~
ebean.default=["models.*","plgmodels.*"]
```
I created 2 entity classes (plgmodels.Person and plgmodels.Group) inheriting Model and with the appropriate annotations.

But when I am starting:

Error injecting constructor, java.lang.IllegalStateException: Bean class plgmodels.Person is not enhanced? at play.db.ebean.EbeanDynamicEvolutions.<init>(EbeanDynamicEvolutions.java:36) at play.db.ebean.EbeanDynamicEvolutions.class(EbeanDynamicEvolutions.java:33) while locating play.db.ebean.EbeanDynamicEvolutions at play.db.ebean.EbeanModule.bindings(EbeanModule.java:23): Binding(class play.api.db.evolutions.DynamicEvolutions to ConstructionTarget(class play.db.ebean.EbeanDynamicEvolutions) eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1) while locating play.api.db.evolutions.DynamicEvolutions while locating play.api.db.evolutions.ApplicationEvolutionsProvider at play.api.db.evolutions.EvolutionsModule.bindings(EvolutionsModule.scala:22): Binding(class play.api.db.evolutions.ApplicationEvolutions to ProviderConstructionTarget(class play.api.db.evolutions.ApplicationEvolutionsProvider) eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1) while locating play.api.db.evolutions.ApplicationEvolutions Caused by: java.lang.IllegalStateException: Bean class plgmodels.Person is not enhanced? at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1334) at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1079) at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1001)

When I put the same classes into "models.*" everything works fine.
Looks like the enhancer is not running.
(I also tried to create another ebean server but to no avail).

Any idea ?

Regards,
PYC

**Comment by jroper** [comment]
Not sure what the problem is, but I'm guessing if you read the [Configuring the sbt plugin](https://www.playframework.com/documentation/2.4.x/JavaEbean#Configuring-the-sbt-plugin) section in the docs, you'll find the answer.

**Comment by pycloux** [comment]
Hi James,
I forgot to say that I obviously tested some modification of SBT configuration (as recommended in the documentation) with:
```
playEbeanModels in Compile := Seq("models.*", "plgmodels.*")
```
but again no result.
I assume from you answer that there is no bug referenced for this.

**Comment by jroper** [comment]
Do you have a multi project setup?  Are you using SBT 0.13.8 or later?  Do you have any other plugins that might be doing some custom compilation?

**Comment by pycloux** [comment]
I am closing the issue.
It was a problem of configuration.
Sorry for this, it seems to be ok now.

**Comment by craigske** [comment]
can you detail the fix?
