### ISSUE TITLE
Update of Ebean to 4.x branch

### ISSUE THREAD

**Issue by pycloux** [playframework/play-ebean#6]
Dear James,

Lurking on the project source code I noticed that you are "upgrading" the Ebean version to the 4.x branch (while to my knowledge the current version in play 2.3.x is the 3.x one).
Please can you tell me with which play version this is supposed to happen (2.4 or later) ?

I also noticed in the code that the Model class of play is being deprecated.
Please can you confirm ?
It could be good to issue an announcement regarding this subject since it would require a bit or time to be ready to a brand new version of Ebean.

Best regards,
PYC

**Comment by jroper** [comment]
https://github.com/playframework/playframework/blob/master/documentation/manual/releases/Migration24.md#ebean
