### ISSUE TITLE
Keeping up with Ebean-orm updates

### ISSUE THREAD

**Issue by corrspt** [playframework/play-ebean#67]
Is there a way for a user to upgrade the ebean version on the plugin (without you guys having to make a new release)? If I just include ebean on my play application's build.sbt file, would it work and use the latest ebean?

Ebean has had several releases in a short amount of time with several bug fixes and new features, but the play-ebean plugin latest stable is on 6.8.1. I know I can make a local build of play ebean and use a local maven repository, but as I'm deploying to heroku it uses maven central to resolve dependencies, as such it's not a good solution to build the plugin locally I think,

Any suggestions/ideas on how to overcome this situation?

Thanks for any help, and thanks a lot for the work on the plugin :+1:

**Comment by wsargent** [comment]
Hi @corrspt currently the plan is here: https://github.com/playframework/playframework/issues/5410 

It'd be nice to get it out before 2.5.0, but I haven't touched it myself -- maybe @benmccann knows more?

**Comment by benmccann** [comment]
We just need someone to cut a new release of play-ebean. And then yeah, we should upgrade Play to use it

**Comment by wsargent** [comment]
Let's see what shiny buttons I can push...

**Comment by wsargent** [comment]
So.  Documentation is here: https://www.playframework.com/documentation/2.4.x/JavaEbean

So version 2.0.0 https://github.com/playframework/play-ebean/tree/2.0.0 uses "6.8.1" and was based off of master branch.  There is a https://github.com/playframework/play-ebean/tree/play-2.4.x branch, but that is very old, currently "1.0.1-SNAPSHOT".  And then the master branch is on Play 2.5.x right now.

I've seen other projects put out Play-2.4 / 2.5 releases concurrently, but it looks like 2.4 branch is so old we might be better off rebranching from master and setting the Play version downwards, then pushing a release from there.  Or we release with 2.5.0, which is at least simpler...

**Comment by marcospereira** [comment]
Hello, @corrspt 

But anyway, you can upgrade to minor versions of Ebean (or any major versions that is binary compatible) at your will. You just need to add the updated dependency to your `build.sbt` file and sbt will try to pick the newest version. Maybe we can add some docs related to it.

**Comment by corrspt** [comment]
@marcospereira 

I'll try it out. I thought I tried that out, but maybe I did some mistake. Will try again, thanks for the tip :+1: 
Having some docs pointing that possibility is interesting as the users won't have to keep bugging you guys for new versions just to update ebean.

**Comment by corrspt** [comment]
@marcospereira : Sorry for the very long delay. I've managed to test and effectively I can upgrade the ebean version. Although I've been bitten by #69 , I'm closing this issue anyway.

Many thanks for the help.
