### ISSUE TITLE
Upgrade/compatibility from Ebean 6.15.1 upwards using play 2.4.6

### ISSUE THREAD

**Issue by oexza** [playframework/play-ebean#69]
play-ebean breaks from Ebean version 6.15.1 upwards, with this error:

    java.lang.NoSuchMethodError: com.avaje.ebean.dbmigration.DdlGenerator: method <init>()V not found

     play.db.ebean.EbeanDynamicEvolutions.generateEvolutionScript(EbeanDynamicEvolutions.java:95)

     play.db.ebean.EbeanDynamicEvolutions.create(EbeanDynamicEvolutions.java:66)

     play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:40)

     play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:149)

     play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:53)

     play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:53)

     play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:44)

     com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)

     com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)

     com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)

     com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)

     com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)

     com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)

     com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)

     com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)

     com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)

     com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)

     com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)

     com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)

     com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)

     com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)

     com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)

     com.google.inject.Guice.createInjector(Guice.java:96)

     com.google.inject.Guice.createInjector(Guice.java:73)

     com.google.inject.Guice.createInjector(Guice.java:62)

     play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)

     play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)

     play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:153)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:150)

     play.utils.Threads$.withContextClassLoader(Threads.scala:21)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:150)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121)

     scala.Option.map(Option.scala:146)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119)

     scala.util.Success.flatMap(Try.scala:231)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111)

     scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)

     scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)

     java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)

     java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)

     java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)

     java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)

     java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by wsargent** [comment]
Seems like this is connected with Play 2.5.0 https://github.com/playframework/playframework/issues/5410

**Comment by marcospereira** [comment]
This is also probably related to Ebean version 6.15.1 not being binary compatible with play-ebean. In other words, an update to this version will need more than just change the version.

**Comment by 0xbaadf00d** [comment]
@marcospereira 6.15.1 don't work out of the box, but the version 6.10.1 seem working like a charm. 

It would be nice if the version 6.10.1 of Ebean could be used rather thant 6.8.x on the plugin for Play 2.4.6. We use Postgresql and the version 6.10.1 is the first to know how handle UUID.

Or do you any tips to use my own compiled version of play-ebean in my Play project ?

**Comment by marcospereira** [comment]
@0xbaadf00d if Ebean 6.10.4 is binary compatible with play-ebean 2.0.0 you won't need to compile your own version, just add Ebean 6.10.4 to `build.sbt` file:

```scala
 libraryDependencies += "org.avaje.ebeanorm" % "avaje-ebeanorm" % "6.10.4"
```

**Comment by 0xbaadf00d** [comment]
@marcospereira thank you for this tips. we have upgraded to prior version 6.10.4 and the projet still pass all unit tests with success and all java.lang.UUID variables on models are now of type UUID on PostgreSQL 9.5.
