### ISSUE TITLE
Documentation: ... "do not expect Ebean-generated getter/setters to be available at compilation time."

### ISSUE THREAD

**Issue by rbygrave** [playframework/play-ebean#71]
Ebean does not generate getter/setter methods as described on page:
https://www.playframework.com/documentation/2.4.x/JavaEbean

> (1) Because Ebean class enhancement occurs after compilation, do not expect Ebean-generated getter/setters to be available at compilation time. If you’d prefer to code with them directly, either add the getter/setters explicitly yourself, or ensure that your model classes are compiled before the remainder of your project, eg. by putting them in a separate subproject.

I believe the question is really about when the Ebean enhancement occurs relative to the Play enhancement - in that it is the Play enhancement that is changing the public field access to getters/setters itself (I believe) and then the Ebean enhancement follows that (changing any field access to persistent fields to Ebean internal interceptor methods). In that sense unless the Ebean enhancement occurs after the Play enhancement THEN lazy loading etc will not work etc.

I way I read it the statement "Ebean-generated getter/setters to be available at compilation time"  ... is misleading.

**Comment by rbygrave** [comment]
Said another way, none of the Ebean generated 'interception methods' are intended for public use - they are all internal use only and ideally non visible to developers using enhanced entity beans.

**Comment by lapidus79** [comment]
Closing, no longer relevant since new play framework releases does not contain Ebean documentation at the play website.
