### ISSUE TITLE
Docs are pointing to 3.0.0-SNAPSHOT version instead of 3.0.0

### ISSUE THREAD

**Issue by talachutla** [playframework/play-ebean#76]
as per the Play 2.5.0 migration guide ( https://www.playframework.com/documentation/2.5.x/JavaEbean )  I have added 

addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "3.0.0-SNAPSHOT") in project/plugins.sbt
But I am getting error as follows 
 unresolved dependency: com.typesafe.sbt#sbt-play-ebean;3.0.0-SNAPSHOT: not found

Seems like jar does not exist

**Comment by marcospereira** [comment]
There is a error at the docs. You should use:
```scala
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "3.0.0")
```

I will keep this issue open until we fix the docs.
