### ISSUE TITLE
Play 2.4.6 / 2.5.0 Java  QueryBeans are not been generating even after I configured. 

### ISSUE THREAD

**Issue by talachutla** [playframework/play-ebean#77]
My Settings are 

playEbeanModels in Compile := Seq("models.*")
playEbeanDebugLevel := 4
playEbeanAgentArgs += ("detect" -> "true") // tried false flag also

Please give provide me the proper settings or  give us a fix

**Comment by marcospereira** [comment]
Hello @talachutla,

QueryBeans are not supported. There is #64 but it stills under discussion. Moreover, please, use the [mailing list](groups.google.com/forum/#!forum/play-framework) to get help.

I'm closing this issue to keep relevant discussion at #64.
