### ISSUE TITLE
Play 2.4.6 compatible & documentation

### ISSUE THREAD

**Issue by 0xbaadf00d** [playframework/play-ebean#80]
Hi,

Please, is it possible to add the 3.0.0 release with `val PlayVersion = "2.4.6"` ?
 
When we replace `addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "2.0.0")` with `addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "3.0.0")`, SBT download Play 2.5.0 libs and broke our corporate projects.

Or, we have cloned our repos and do modifications to backport on play 2.4.6, but we dont know how to use our project on an existing Play project. addSbtPlugin dont seem to accep path to another SBT project.

Could you provide a documentation about building and using "as developer" play-ebean project ?

**Comment by oexza** [comment]
it won't work! 3.0.0 has changes that are only compatible with play 2.6

**Comment by 0xbaadf00d** [comment]
2.6 ? But only 2.5.0 was release last week and is referenced on all build.sbt files found on this repos.

**Comment by oexza** [comment]
whoops!!!! sorry 2.5 i meant to say, i've edited my comment.

**Comment by 0xbaadf00d** [comment]
ok no prob. Maybe you have to update the play templat. When we run `activator new my-project` (and choose full java project). plugins.sbt file still contain reference to play-ebean 1.0.0

**Comment by schmitch** [comment]
I will close this as of now since it probably won't be done against 2.4.x.
