### ISSUE TITLE
 find and update record feature is missing

### ISSUE THREAD

**Issue by komalkamble** [playframework/play-ebean#86]
To update a record , developer need to find record from db then need to set the new values for required fields/column and call update method on that ebean object. 
If I want to update the record which is find/retrieved using  the multiple condition using AND operator, when I call update() on that  ebean object then record gets updated only on the basis of id. 
I am working on multi tenant Saas application . 
Is there update() method on find like Ebean.find (Test.class).where ().eq ("").eq ("").update ()

**Comment by marcospereira** [comment]
This is more related to Ebean itself, instead of play-ebean. I suggest you to see the [docs about bulk updates](http://ebean-orm.github.io/docs/persist/#bulkupdate) and if it does not solve your problem, get help from [ebean community](http://ebean-orm.github.io/support).

**Comment by komalkamble** [comment]
Ok Marcos.  Thank you for providing a right direction.

*Regards,*
*Komal Kamble*
Software Engineer
Infiverve Technologies Pvt. Ltd. <http://www.infiverve.com/> | Flint IT
Automation <http://www.getflint.io/>
M: +91 8149639134 | Skype: komal_infiverve | twitter: @ImpulseKomal
