### ISSUE TITLE
It's impossible to filter jsonb arrays with ebean and psql (with query symbol)?

### ISSUE THREAD

**Issue by ArkadyKarev** [playframework/play-ebean#88]
Hello!
Our DB has several entities with @DbJsonB fields, that holds arrays of strings inside. It could be just great to have ability to execute queries with conditions for jsonb fields, like
`select * from foo_bars where jsonb_tags ? some_tag;`
_query symbol means that jsonb_tags array contains some_tag._
or
```
@ManyToMany
@Where(clause = "roles ? SOME_ROLE")
private List<User> usersWithSomeRole;
```
[psql docs](http://www.postgresql.org/docs/9.4/static/functions-json.html)

Is it possible to use this syntax with ebean?
For now I have to use plain jdbc connection in some cases with `play.db.DB.getConnection()`. All my tries with ebean ends with SQLExceptions, with the reason 

> Caused by: org.postgresql.util.PSQLException: No value specified for parameter _any_number_.

May be it's possible to escape query character some way?

**Comment by wsargent** [comment]
Hi @ArkadyKarev this is a bug tracker, so it's not possible to do anything without a reproducible test case that shows what the behavior is and why it's considered to be a bug in play-ebean.  If you are looking for help, please contact https://ebean-orm.github.io/support for ebean questions.

**Comment by ArkadyKarev** [comment]
@wsargent Got it, sorry.
