### ISSUE TITLE
DefaultEbeanConfig does not recognize .** in config

### ISSUE THREAD

**Issue by xunnanxu** [playframework/play-ebean#89]
Ebean enhancer supports .** which means to recursively search for classes to enhance. However the config class doesn't understand that and causes exceptions to be thrown at runtime.

The related code is

                    if (load.endsWith(".*")) {
                        classes.addAll(play.libs.Classpath.getTypes(environment, load.substring(0, load.length()-2)));
                    } else {
                        classes.add(load);
                    }

This causes ".**" to be added as the literal class name and causes injection to fail at the end.

**Comment by rbygrave** [comment]
> Ebean enhancer supports .**

Note that Ebean does support a .** suffix but it not longer uses it in the sense that it now always recursively searches sub-packages.

That is, you don't really need to specify a suffix of .** anymore from an Ebean perspective.  I can't remember when that change came in but it's been in for a while.

**Comment by xunnanxu** [comment]
Hi @rbygrave thanks for the information. I thought ** was required and that's what we are currently using. I'll definitely test what you said when I have a chance.

**Comment by rbygrave** [comment]
No problem.  

I've noted that some of the Ebean documentation and examples still had the .** even though it effectively was not used anymore.  I think I have tidied that up now but that didn't help things.

**Summary:**
To be explicit, I'd say this is really a documentation issue and not a bug in play-ebean DefaultEbeanConfig. As such it probably should be closed.

**Comment by xunnanxu** [comment]
Closing this issue as it turns out it's due to related ebean code left there for compatibility reasons.

**Comment by xunnanxu** [comment]
Thanks to @rbygrave for clarification.
