### ISSUE TITLE
Change to MIT License

### ISSUE THREAD

**Issue by 0xbaadf00d** [playframework/play-ebean#93]
Since play-ebean has been converted to a simple _playframework_ module. It could be nice to review the used license too. Why not using MIT who is more permissive and, i think, will allow more user to contribute to this project.

**Comment by schmitch** [comment]
What's wrong with Apache 2.0 ?

**Comment by 0xbaadf00d** [comment]
This project is Apache 2.0 licensed ? I find nothing about it on source files except this following header in 1 or 2 files :

```
/*
 * Copyright (C) 2009-2015 Typesafe Inc. <http://www.typesafe.com>
 */
```

Maybe add a _LICENSE_ file and update header of each source files ?

Apache 2.0 seems a good license too, more retristrive, but good too.

**Comment by schmitch** [comment]
Actually Copyright != License. Yeah this project misses License.txt, but under maven central you see the Apache 2 license.

**Comment by benmccann** [comment]
Added LICENSE file to make it easier to find licensing. See https://github.com/playframework/play-ebean/commit/adb38207d8c1e0d7f24b330fe4f4be8dd82487e3
