### ISSUE TITLE
sbt-play-ebean % 3.1.0 missing annotations

### ISSUE THREAD

**Issue by almothafar** [playframework/play-ebean#96]
I tried to update the plugin inside my project from

`addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "3.0.2")
`
to 

`addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "3.1.0")`

But It seems load wrong jar files, first it let ivy download `org.avaje.ebean` version 8.2.3 not latest one (8.4.1), while the previous version ("sbt-play-ebean" % "3.0.2") uses `avaje-ebeanorm-7.6.1` in classpath

The annotations that I noticed that not working : 

```
import com.avaje.ebean.annotation.ConcurrencyMode;
import com.avaje.ebean.annotation.EntityConcurrencyMode;
import com.avaje.ebean.annotation.EnumMapping;
```

Not sure what the issue 😕

**Comment by 0xbaadf00d** [comment]
Hi @almothafar, 

Ebean since 7.x had a lot of modifications / upgrades. You can read Ebean release notes at https://github.com/ebean-orm/ebean/releases.

**Comment by almothafar** [comment]
@0xbaadf00d Thanks, I need to check migration and see, I wish if there is any documentation update in play site or read me here at least, but for released I checked them here: 

https://mvnrepository.com/artifact/com.typesafe.play/play-ebean_2.11
And 
https://mvnrepository.com/artifact/org.avaje.ebean/ebean/8.4.1

Seems they available from week.
