### ISSUE TITLE
batch insert not working

### ISSUE THREAD

**Issue by lzhang32** [playframework/play-ebean#98]
Hi,

I am using Ebean (PlayEbean V.1.0.0) for MySQL. And I found that batch insert seem not work for me.
A similar problem is at http://stackoverflow.com/questions/32274481/ebean-batch-not-working

My code snippet is as follows. Note that I have JdbcTransaction and try to turn off auto-commit 
for MySQL by "transaction.getConnection().setAutoCommit(false);". It does not work.
In transaction object, the "autocommit" value is still "true".

Any suggestions?  how can I set "autocommit" to false?  

` EbeanServer ebeanServer = Ebean.getServer(null);
    Transaction transaction = ebeanServer.beginTransaction();
    try {

```
  **transaction.getConnection().setAutoCommit(false);**

  transaction.setPersistCascade(false);
  transaction.setBatchMode(true);
  transaction.setBatchSize(100);
  transaction.setBatchGetGeneratedKeys(false);

  for (ProjectFeature projectFeature : projectFeatures ) {
     ebeanServer.save(projectFeature);
  }
  transaction.commit();

} catch(Exception ex) {
   LOG.error("ERROR in batchInsertProjectFeatures : " + ex);

} finally {
  transaction.end();
}`
```

**Comment by 0xbaadf00d** [comment]
Do you have the possibility to use/test with Play Ebean 3.1.0 ? Maybe this issus has been fixed.

**Comment by lzhang32** [comment]
Because I am using Play-v2.4, So I think PlayEbean v.1.0.0 is the latest one I can use. Any other suggestions? Why I can not set autocommit=false?

Thanks much!

**Comment by marcospereira** [comment]
Not able to reproduce the problem.
